# Generated by Django 3.2.5 on 2021-11-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='data_teste_hiv_pos',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='teste_hiv_pos',
        ),
    ]
