# Generated by Django 3.2.5 on 2021-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0002_auto_20211116_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='data_diagnostico',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_inicio_tarv',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_inscricao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_morte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='inscrito_programa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='morreu',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
