# Generated by Django 3.2.5 on 2021-11-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0004_alter_paciente_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='transferido_em',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='localidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
