# Generated by Django 3.2.5 on 2021-11-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0005_auto_20211116_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='data_inscricao',
            new_name='data_inscricao_programa',
        ),
    ]
