# Generated by Django 3.2.5 on 2021-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0006_rename_data_inscricao_inscricao_data_inscricao_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
