# Generated by Django 3.2.5 on 2021-11-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0007_alter_inscricao_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='criptococose',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='diabetes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='gravidez',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='hepatite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='hta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='lactante',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='s_kapose',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='tb',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ultima_ctz_data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ultima_cv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ultimo_cd4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='via_positivo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
