# Generated by Django 3.2.5 on 2021-11-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0008_auto_20211116_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultaclinica',
            name='diagnostico_its',
        ),
        migrations.AlterField(
            model_name='consultaclinica',
            name='data_consulta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultaclinica',
            name='data_proxima_consulta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultaclinica',
            name='gravidez',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultaclinica',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='consultaclinica',
            name='lactante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
