# Generated by Django 3.2.5 on 2021-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0010_alter_consultaclinica_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='data_levantamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='data_proximo_levantamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='dosagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='regime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
