# Generated by Django 3.2.5 on 2021-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0011_auto_20211117_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='data_inicio_tarv',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
