# Generated by Django 3.2.5 on 2021-07-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('openmrs', models.CharField(blank=True, max_length=100, null=True)),
                ('categoryOptionCombo', models.CharField(blank=True, max_length=200, null=True)),
                ('attributeOptionCombo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=10)),
                ('mes', models.CharField(choices=[('Jan', 'Janeiro'), ('Feb', 'Fevereiro'), ('Mar', 'Março'), ('Apr', 'Abril'), ('May', 'Maio'), ('Jun', 'Junho'), ('Jul', 'Julho'), ('Aug', 'Agosto'), ('Sep', 'Setembro'), ('Oct', 'Outubro'), ('Nov', 'Novembro'), ('Dec', 'Dezembro')], max_length=50)),
                ('period_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OpenmrsURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('instance_name', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('dataSet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
            ],
            options={
                'verbose_name': 'Health Facility',
                'verbose_name_plural': 'Health Facilities',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province'),
        ),
        migrations.CreateModel(
            name='DataElementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('dataElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataelement')),
                ('healthFacility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.healthfacility')),
            ],
        ),
        migrations.AddField(
            model_name='dataelement',
            name='dataSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset'),
        ),
    ]
