# Generated by Django 3.2.5 on 2021-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmrsurl',
            name='openmrs_us',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
